# Generated by Django 4.2.3 on 2023-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='keyword',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
