# Generated by Django 4.2.3 on 2023-08-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_document_dealinfo_comment_dealinfo_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='keyword',
        ),
    ]
