# Generated by Django 4.2.3 on 2023-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_remove_video_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='druganddoorcol',
            name='users_found_channel',
            field=models.ManyToManyField(to='parser_app.profile'),
        ),
        migrations.AddField(
            model_name='druganddoorfield',
            name='users_found_channel',
            field=models.ManyToManyField(to='parser_app.profile'),
        ),
    ]
