# Generated by Django 4.2.3 on 2023-09-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_druganddoorcol_users_found_channel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druganddoorcol',
            old_name='users_found_channel',
            new_name='users_found_pipeline',
        ),
        migrations.RenameField(
            model_name='druganddoorfield',
            old_name='users_found_channel',
            new_name='users_found_pipeline',
        ),
    ]
