# Generated by Django 4.2.3 on 2023-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_rename_users_found_channel_druganddoorcol_users_found_pipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealinfo',
            name='users_found_pipeline',
            field=models.ManyToManyField(to='parser_app.profile'),
        ),
    ]
