# Generated by Django 4.2.3 on 2023-09-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_remove_users_found_remove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remove',
            name='users_found_remove',
        ),
    ]
