# Generated by Django 4.2.3 on 2023-09-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_remove_remove_users_found_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='remove',
            name='users_found_remove',
            field=models.ManyToManyField(to='parser_app.profile'),
        ),
    ]
